// ── SHARED DATA ─────────────────────────────────────────────

export const SERVICES = [
  {
    icon: 'Globe',
    n: '// 01',
    title: 'Conception de Site Web',
    desc: "Création de sites web modernes, responsive et optimisés pour convertir vos visiteurs en clients. Du portfolio à la plateforme e-commerce, chaque page est conçue avec soin.",
    price: 'À partir de 220 000 FCFA',
    del: '5-7 jours',
    img: '/images/service/creation%20de%20site%20web.webp',
    features: ['Design sur-mesure','SEO optimisé','Formulaire de contact','Hébergement 1 an offert','Formation incluse'],
    slug: 'site-vitrine',
    color: '#88ca53',
  },
  {
    icon: 'Map',
    n: '// 02',
    title: 'Cartes Interactives & Dashboards',
    desc: "Intégration de cartes interactives Mapbox / Leaflet et de dashboards de visualisation de données. Vos données brutes deviennent des interfaces lisibles et actionnables.",
    price: 'Sur devis',
    del: '7-14 jours',
    img: '/images/service/dasbord.webp',
    features: ['Cartes Mapbox / Leaflet','Dashboards data temps réel','Filtres et exports','Graphiques interactifs','API de données'],
    slug: 'cartes-dashboards',
    color: '#88ca53',
  },
  {
    icon: 'Server',
    n: '// 03',
    title: 'API & Backend Robustes',
    desc: "Conception d'API RESTful sécurisées avec Django ou Flask. Authentification JWT, gestion des rôles, intégration Mobile Money et déploiement sur Vercel ou PythonAnywhere.",
    price: 'À partir de 200 000 FCFA',
    del: '7-14 jours',
    img: '/images/service/api.webp',
    features: ['REST avec Django / Flask','Authentification JWT','Intégration Mobile Money','Gestion des rôles','Déploiement cloud'],
    slug: 'api-backend',
    color: '#88ca53',
  },
  {
    icon: 'Wrench',
    n: '// 04',
    title: 'Maintenance & Support',
    desc: "Suivi technique, corrections de bugs, mises à jour de sécurité et améliorations continues. Vous vous concentrez sur votre métier, AKATech s'occupe du reste.",
    price: 'À partir de 25 000 FCFA/mois',
    del: 'Contrat mensuel',
    img: '/images/service/maintenence.webp',
    features: ['Mises à jour régulières','Corrections de bugs','Sauvegardes automatiques','Support prioritaire','Rapport mensuel'],
    slug: 'maintenance',
    color: '#88ca53',
  },
  {
    icon: 'MapPin',
    n: '// 05',
    title: 'Fiche Google My Business',
    desc: "Création ou optimisation de votre fiche Google (NAP, catégories, photos, description SEO local) et suivi mensuel : réponse aux avis, publications et statistiques.",
    price: 'À partir de 20 000 FCFA',
    del: '1-2 jours',
    img: '/images/service/fiche-google.webp',
    features: ['Création ou optimisation','SEO local (NAP)','Photos & description','Suivi mensuel & avis','Statistiques de fiche'],
    slug: 'google-my-business',
    color: '#88ca53',
  },
]

export const PROJECTS = [
  {
    id: 1,
    title: 'ShopCI',
    type: 'E-Commerce',
    subtitle: 'Marketplace E-commerce',
    desc: "Marketplace multi-vendeurs conçue pour répondre aux problèmes de fiabilité, de visibilité et de gestion des ventes dans le e-commerce local ivoirien.",
    img: '/images/projects/shopci-preview.webp',
    imgMobile: '/images/projects/shopci-responsive.webp',
    tech: ['React', 'Django', 'Bootstrap 5', 'Vercel + PythonAnywhere'],
    url: 'https://shop-ci.vercel.app/',
    result: '↑ Multi-vendeurs',
    live: true,
    year: '2024',
    progress: 65,
  },
  {
    id: 2,
    title: 'TechFlow',
    type: 'Site Vitrine',
    subtitle: 'Site Vitrine Professionnel',
    desc: "Site vitrine moderne destiné à présenter une activité technologique de manière claire et professionnelle. UI propre, responsive et déployé en production.",
    img: '/images/projects/techflow-preview.webp',
    imgMobile: '/images/projects/techflow.webp',
    tech: ['HTML', 'Tailwind CSS', 'JavaScript', 'Vercel'],
    url: 'https://techflow-ten.vercel.app/',
    result: '↑ UI responsive',
    live: true,
    year: '2024',
    progress: 97,
  },
  {
    id: 3,
    title: 'TerraSafe',
    type: 'Marketplace Foncière',
    subtitle: 'Marketplace Foncière',
    desc: "Plateforme foncière visant à réduire les risques d'arnaques liées à la vente de terrains. Backend sécurisé avec authentification et recherche avancée.",
    img: '/images/projects/terrasafe-preview.webp',
    imgMobile: '/images/projects/terrasafe.webp',
    tech: ['Python / Flask', 'MySQL', 'JavaScript', 'Bootstrap 5'],
    url: 'https://wthomassss06.pythonanywhere.com',
    result: '↑ Auth sécurisée',
    live: true,
    year: '2024',
    progress: 85,
  },
  {
    id: 4,
    title: 'Chap-chapMAP',
    type: 'Application',
    subtitle: 'Navigation Intelligente',
    desc: "Application de cartographie intelligente permettant de localiser un utilisateur en temps réel et de calculer des itinéraires optimisés.",
    img: '/images/projects/chapchapmap-preview.webp',
    imgMobile: '/images/projects/chapchapmap.webp',
    tech: ['JavaScript', 'Leaflet.js', 'OSRM API', 'Geolocation API'],
    url: null,
    result: '↑ GPS temps réel',
    live: false,
    year: '2023',
    progress: 100,
  },
  {
    id: 5,
    title: 'ElvisMarket',
    type: 'E-Commerce',
    subtitle: 'Interface E-commerce',
    desc: "Interface e-commerce développée pour expérimenter la gestion d'état, le panier dynamique et l'optimisation de l'UX sur mobile.",
    img: '/images/projects/elvismarket-preview.webp',
    imgMobile: '/images/projects/elvismarket.webp',
    tech: ['HTML', 'JavaScript', 'Tailwind CSS', 'LocalStorage'],
    url: null,
    result: '↑ Panier dynamique',
    live: false,
    year: '2023',
    progress: 100,
  },
  {
    id: 6,
    title: 'MonCashJour',
    type: 'Dashboard',
    subtitle: 'Gestion de Ventes',
    desc: "Application de gestion de ventes quotidiennes pour petits commerçants, avec visualisation des performances et export des données.",
    img: '/images/projects/moncashjour-preview.webp',
    imgMobile: '/images/projects/moncashjour.webp',
    tech: ['HTML', 'JavaScript', 'Tailwind CSS', 'Chart.js'],
    url: null,
    result: '↑ Export CSV',
    live: false,
    year: '2023',
    progress: 100,
  },
  {
    id: 7,
    title: 'LivreurTrack Pro',
    type: 'Dashboard',
    subtitle: 'Suivi Logistique',
    desc: "Système de suivi logistique simulant un workflow réel de livraison, avec validation par photo et suivi d'étapes.",
    img: '/images/projects/livreurtrack-preview.webp',
    imgMobile: '/images/projects/livreurtrack.webp',
    tech: ['JavaScript', 'Bootstrap 5', 'LocalStorage', 'Camera API'],
    url: null,
    result: '↑ Workflow 5 étapes',
    live: false,
    year: '2023',
    progress: 100,
  },
  {
    id: 8,
    title: 'LinkedIn Banner Pro',
    type: 'SaaS',
    subtitle: 'Générateur SaaS',
    desc: "Outil SaaS en cours de développement permettant de générer des bannières LinkedIn professionnelles via un éditeur visuel.",
    img: '/images/projects/linkedin-banner-preview.webp',
    imgMobile: '/images/projects/linkedin-banner.webp',
    tech: ['JavaScript', 'Canvas API', 'Tailwind CSS'],
    url: null,
    result: '↑ Éditeur visuel',
    live: false,
    year: '2025',
    progress: 30,
  },
  {
    id: 9,
    title: 'Tati',
    type: 'Portfolio',
    subtitle: 'Portfolio & Vitrine Moderne',
    desc: "Portfolio personnel double fonction : vitrine professionnelle et page de présentation. Animations fluides, thème sombre/clair, design 100% responsive.",
    img: '/images/projects/tati-preview.webp',
    imgMobile: '/images/projects/tati.webp',
    tech: ['React', 'Tailwind CSS', 'Framer Motion', 'Vercel'],
    url: 'https://tatii.vercel.app/',
    result: '↑ Thème sombre/clair',
    live: true,
    year: '2024',
    progress: 100,
  },
  {
    id: 10,
    title: 'MK Studio',
    type: 'Portfolio',
    subtitle: 'Portfolio Graphiste Client',
    desc: "Portfolio professionnel sur-mesure pour un client graphiste. Galerie immersive, animations soignées et thème sombre élégant.",
    img: '/images/projects/mk-preview.webp',
    imgMobile: '/images/projects/mk.webp',
    tech: ['React', 'Tailwind CSS', 'Framer Motion', 'Vercel'],
    url: 'https://mory01ff.vercel.app/',
    result: '↑ Design sur-mesure',
    live: true,
    year: '2024',
    progress: 100,
  },
  {
    id: 11,
    title: 'ManoBeat 777',
    type: 'E-Commerce',
    subtitle: 'Portfolio Beatmaker',
    desc: "Portfolio d'un beatmaker ivoirien : découvrez et écoutez ses créations directement en ligne, puis achetez vos beats préférés via WhatsApp en quelques clics.",
    img: '/images/projects/beatstore-preview.webp',
    imgMobile: '/images/projects/beatstore.webp',
    tech: ['React', 'Tailwind CSS', 'Howler.js', 'Vercel'],
    url: 'https://xxx-x.vercel.app/',
    result: '↑ Écoute en ligne',
    live: true,
    year: '2025',
    progress: 100,
  },
  {
    id: 12,
    title: 'New Horizon Service',
    type: 'Application',
    subtitle: 'Location de Résidences',
    desc: "Plateforme de location de résidences meublées haut de gamme. Interface moderne côté client, backend Flask sécurisé avec API REST, recherche avancée et gestion des disponibilités.",
    img: '/images/projects/newhorizon-preview.webp',
    imgMobile: '/images/projects/newhorizon.webp',
    tech: ['Next.js', 'Flask', 'Python', 'MySQL', 'Vercel'],
    url: 'https://new-horizonservice.vercel.app/',
    result: '↑ Réservation en ligne',
    live: true,
    year: '2025',
    progress: 100,
  },
  {
    id: 13,
    title: 'AKATech',
    type: 'Agence Digitale',
    subtitle: 'Agence Digitale Abidjan',
    desc: "Site officiel de l'agence AKATech, qui accompagne les entrepreneurs et PME en Côte d'Ivoire dans leurs projets digitaux.",
    img: '/images/projects/akatech-preview.webp',
    imgMobile: '/images/projects/akatech.webp',
    tech: ['Next.js 15', 'Framer Motion', 'WebGL Iridescence', 'Vercel'],
    url: 'https://akatech.vercel.app/',
    result: '↑ Site officiel',
    live: true,
    year: '2025',
    progress: 100,
  },
  {
    id: 14,
    title: 'Université les Anges',
    type: 'Institutionnel',
    subtitle: 'Site Institutionnel',
    desc: "Site institutionnel moderne pour un établissement d'enseignement supérieur. Présentation des filières, admissions et vie étudiante dans une interface claire et professionnelle.",
    img: '/images/projects/universitelesanges-preview.webp',
    imgMobile: '/images/projects/universitelesanges.webp',
    tech: ['HTML', 'CSS', 'Bulma', 'Bootstrap', 'Vercel'],
    url: 'https://universitelesanges.vercel.app/',
    result: '↑ Image institutionnelle',
    live: true,
    year: '2025',
    progress: 100,
  },
  {
    id: 15,
    title: 'Nexura',
    type: 'Marketplace',
    subtitle: 'Marketplace Nouvelle Génération',
    desc: "Marketplace nouvelle génération : location de résidences meublées, motos & véhicules, bureaux & salles de conférence, terrains & immobilier. Auth sécurisée, KYC intégré, temps réel.",
    img: '/images/projects/nexura-preview.webp',
    imgMobile: '/images/projects/nexura-responsive.webp',
    tech: ['Next.js 14', 'Django REST', 'PostgreSQL', 'WebSockets', 'Redis & Celery'],
    url: 'https://nexura-one.vercel.app/',
    result: '↑ Multi-catégories',
    live: true,
    year: '2025',
    progress: 100,
  },
  {
    id: 16,
    title: 'KokoEat',
    type: 'Livraison',
    subtitle: 'Livraison Alimentaire',
    desc: "Application de livraison de repas pensée pour le marché ivoirien. Commande en ligne, suivi en temps réel et paiement Mobile Money.",
    img: '/images/projects/kokoeat-preview.webp',
    imgMobile: '/images/projects/kokoeat-responsive.webp',
    tech: ['React', 'Django REST', 'PostgreSQL', 'Vercel'],
    url: null,
    result: '↑ Suivi temps réel',
    live: false,
    year: '2025',
    progress: 80,
  },
  {
    id: 17,
    title: 'Jean Edy · Portfolio',
    type: 'Portfolio',
    subtitle: 'Portfolio React UI Avancé',
    desc: "Portfolio personnel développé pour un autre développeur basé à Abidjan. Trilingue FR/EN/RU, animations soignées et système de design sur-mesure.",
    img: '/images/projects/jean-edy-preview.webp',
    imgMobile: '/images/projects/jean-edy.webp',
    tech: ['React 18', 'Vite', 'GSAP', 'Framer Motion', 'TailwindCSS'],
    url: 'https://jean-edy-dev.vercel.app/',
    result: '↑ Présence pro en ligne',
    live: true,
    year: '2026',
    progress: 100,
  },
  {
    id: 18,
    title: 'MD Laverie Pressing',
    type: 'Site Vitrine',
    subtitle: 'Site Vitrine Pressing',
    desc: "Site vitrine complet pour un pressing à Abidjan. Hero animé, grille de tarifs claire et formulaire de contact pour la prise de rendez-vous en ligne.",
    img: '/images/projects/laverie-preview.webp',
    imgMobile: '/images/projects/laverie.webp',
    tech: ['React 18', 'Vite', 'GSAP', 'React Router v6', 'EmailJS'],
    url: 'https://laverie-plus.vercel.app/',
    result: '↑ Prises de RDV en ligne',
    live: true,
    year: '2025',
    progress: 100,
  },
]

export const TESTIMONIALS = [
  { name: 'Tanoh Calvin', role: 'Gérant · MEUBLE CI', project: 'Site Vitrine', rating: 5, text: "AKATech a créé notre site en moins d'une semaine. Résultat professionnel, rapide et exactement ce qu'on voulait. On recommande sans hésiter !", img: '/images/clients/client-1.webp', result: '↑ Visibilité x3' },
  { name: 'Gnihan Tatiana', role: 'Cuisinière & Artisane du fil', project: 'Portfolio', rating: 5, text: "Mon portfolio en ligne tourne depuis 3 mois. Les clients me contactent directement depuis le site. Exactement ce dont j'avais besoin.", img: '/images/clients/client-2.webp', result: '↑ 3 nouveaux clients' },
  { name: 'Yao Darwell', role: 'Graphiste · Designer', project: 'Portfolio', rating: 5, text: "Mon portfolio m'a permis d'obtenir 3 nouveaux clients en un mois. Design superbe, animations fluides. AKATech comprend vraiment les créatifs.", img: '/images/clients/client-3.webp', result: '↑ CA en 30 jours' },
]

export const TEAM = [
  { name: "M'Bollo Aka Elvis", role: 'Fondateur & Développeur Full-Stack', skills: ['React','Django','Python','Next.js','PostgreSQL'], bio: "Développeur passionné basé à Abidjan avec 3+ ans d'expérience. Spécialisé dans les solutions web pour le marché africain.", img: '/images/about-4.webp' },
]

export const STATS = [
  { val: 18, suffix: '+', label: 'Projets livrés' },
  { val: 100, suffix: '%', label: 'Clients satisfaits' },
  { val: 3, suffix: '+', label: "Années d'expérience" },
  { val: 48, suffix: 'h', label: 'Support max' },
]

export const BLOG_POSTS = [
  {
    slug: 'pourquoi-votre-business-a-besoin-dun-site-web',
    title: 'Pourquoi votre business a besoin d\'un site web en 2025',
    excerpt: 'En Côte d\'Ivoire, plus de 60% des consommateurs recherchent une entreprise en ligne avant d\'acheter. Voici pourquoi ne pas avoir de site web vous coûte des clients chaque jour.',
    category: 'Stratégie Digitale',
    date: '2025-01-15',
    readTime: '5 min',
    img: '/images/about-1.webp',
  },
  {
    slug: 'mobile-money-integration-site-ecommerce',
    title: 'Intégrer Mobile Money sur votre site e-commerce en Côte d\'Ivoire',
    excerpt: 'MTN MoMo, Orange Money, Wave... Comment accepter les paiements mobiles sur votre boutique en ligne et multiplier vos conversions de 3x.',
    category: 'E-Commerce',
    date: '2025-02-10',
    readTime: '8 min',
    img: '/images/projects/moncashjour-preview.webp',
  },
  {
    slug: 'react-vs-wordpress-pour-pme-africaines',
    title: 'React ou WordPress : que choisir pour votre PME africaine ?',
    excerpt: 'Deux approches, deux philosophies. On compare les coûts, la performance et la maintenance pour vous aider à faire le bon choix selon votre budget.',
    category: 'Développement Web',
    date: '2025-03-05',
    readTime: '6 min',
    img: '/images/about-2.webp',
  },
  {
    slug: 'seo-local-abidjan-guide-complet',
    title: 'SEO Local à Abidjan : le guide complet pour apparaître en premier sur Google',
    excerpt: 'Votre concurrent apparaît en premier sur Google et vous non ? Voici les 7 optimisations SEO locales qui font la différence pour les entreprises abidjanaises.',
    category: 'SEO',
    date: '2025-03-20',
    readTime: '10 min',
    img: '/images/about-3.webp',
  },
]

export const FAQ_ITEMS = [
  { q: 'Comment se déroule le paiement de mon site ?', a: "Le paiement se fait en deux fois : 50% à la commande pour démarrer le projet, et les 50% restants à la livraison, juste avant de recevoir les fichiers finaux et les accès." },
  { q: "Pourquoi un acompte est-il demandé avant de commencer ?", a: "L'acompte confirme votre commande et permet de démarrer le développement immédiatement, de récupérer vos contenus (logo, textes, photos) et de garantir le délai annoncé. Sans acompte, le projet n'est pas priorisé dans le planning." },
  { q: 'Quels moyens de paiement acceptez-vous ?', a: "Orange Money, MTN Mobile Money, Wave ou virement bancaire. Vous précisez votre moyen préféré au moment de la commande et les coordonnées correspondantes vous sont envoyées." },
  { q: 'Quel est le délai pour recevoir mon site ?', a: "Cela dépend du pack choisi : 3 à 5 jours pour un portfolio simple, davantage pour une vitrine, une boutique e-commerce ou une application plus complexe. Le délai exact est précisé dans le devis et démarre dès réception de l'acompte et de vos contenus." },
  { q: 'Quand mon site est-il mis en ligne ?', a: "Une fois le solde réglé. Avant cela, un lien de prévisualisation vous est partagé pour valider le design et le contenu." },
  { q: "Puis-je voir mon site avant qu'il soit en ligne ?", a: "Oui, toujours. Vous recevez un lien de prévisualisation pour tester le site, faire vos retours et demander des ajustements avant la mise en ligne officielle." },
  { q: 'Combien de modifications sont incluses ?', a: "Les petites corrections — textes, couleurs, ajustements visuels — sont incluses pendant la phase de validation. Les modifications majeures, comme un changement de structure ou l'ajout de pages, font l'objet d'un devis complémentaire." },
  { q: 'Quel pack choisir pour mon projet ?', a: "Tout dépend de vos besoins : portfolio, vitrine, boutique e-commerce ou application plus complexe type SaaS. Un conseil gratuit est proposé lors du brief initial pour identifier le pack le plus adapté." },
  { q: "Le nom de domaine et l'hébergement sont-ils vraiment gratuits ?", a: "Oui, la première année est offerte sur tous les packs. Après cette période, vous payez simplement le renouvellement — environ 15 000 à 30 000 FCFA par an selon le domaine — avec un rappel envoyé avant l'expiration." },
  { q: 'Quels contenus dois-je fournir ?', a: "Votre logo, vos photos, vos textes de présentation et vos informations de contact. Plus ces éléments arrivent vite, plus le développement avance rapidement." },
  { q: "Je n'ai pas de logo ni de textes, pouvez-vous m'aider ?", a: "Oui. AKATech peut proposer un logo simple, utiliser des visuels libres de droits adaptés à votre activité, ou rédiger une trame de textes professionnels que vous ajustez ensuite. Ces services s'ajoutent au devis initial." },
  { q: 'Qui gère mon site après la livraison ?', a: "Vous. Tous les accès — administration, hébergement, nom de domaine — vous sont transmis, ainsi qu'un tutoriel simple pour modifier vos textes et images sans dépendre de quelqu'un d'autre." },
  { q: "Que se passe-t-il si le délai annoncé n'est pas respecté ?", a: "C'est rare, mais si cela arrive du fait d'AKATech, une pénalité s'applique sur le montant total et vous pouvez demander l'annulation du projet avec un remboursement partiel. Ces conditions figurent dans le devis signé." },
  { q: 'Mon site a un bug après la livraison, que faites-vous ?', a: "Tout bug lié au développement est corrigé gratuitement pendant le mois suivant la livraison — inclus dans le pack le plus complet, possible en option sur les autres packs." },
  { q: 'Comment commander mon site ?', a: "Trois étapes : échange sur votre projet et le pack adapté, envoi d'un devis avec l'acompte de 50%, puis dès réception du paiement le développement démarre." },
]