'use client'
import { createContext, useContext, useEffect, useState } from 'react'

export const LANGUAGES = [
  { code: 'fr', label: 'FR', name: 'Francais' },
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'es', label: 'ES', name: 'Espanol' },
]

const TRANSLATIONS = {
  fr: {
    home: 'Accueil', about: 'À propos', services: 'Services', projects: 'Réalisation',
    pricing: 'Tarifs', blog: 'Blog', contact: 'Contact', explorer: 'Explorer',
    startProject: 'DEMARRER MON PROJET', backToSite: 'Retour au site',
    ourProjects: 'Nos realisations', studio: 'Le Studio.', portfolio: 'Portfolio',
    selectedProjects: 'Projets selectionnes', transparentQuotes: 'Devis transparents',
    adviceNews: 'Conseils & actualites', service: 'Service', whatWeOffer: 'Ce que nous proposons',
    aboutTeam: 'Notre equipe, Abidjan', talkProject: 'Parlons de ton projet',
    darkMode: 'Mode sombre', lightMode: 'Mode clair', language: 'Langue',
    menu: 'Menu', close: 'Fermer', homeAria: "Retour a l'accueil",
    freeQuote: 'Devis gratuit', viewServices: 'Voir les services', chooseSolution: 'Choisissez votre solution',
    service_site_vitrine: 'Conception de Site Web', service_cartes_dashboards: 'Cartes Interactives & Dashboards',
    service_maintenance: 'Maintenance & Support', service_google_my_business: 'Fiche Google My Business',
    service_chatbot_ia: 'Intégration IA Chatbot', service_paiement_en_ligne: 'Intégration de Paiement en Ligne',
    servicesHero: 'De la consultation au déploiement, chaque service est conçu pour répondre aux réalités du marché ivoirien.',
    projectsHero: 'Sites vitrines, e-commerces, SaaS, portfolios… Chaque réalisation est une histoire de transformation digitale réussie.',
    deliveredProjects: 'réalisations livrées', satisfied: 'satisfaits', online: 'en ligne', inProgress: 'En cours',
    pricingHero: 'Des prix honnêtes adaptés au marché africain, avec devis gratuit et sans engagement.', pricingTitle: 'Des offres claires, pour chaque étape.',
    aboutHero: "AKATech accompagne les entrepreneurs et PME en Côte d'Ivoire qui veulent une présence digitale sérieuse.", aboutTitle: "Votre croissance digitale, c'est notre mission.",
    about_results: 'Résultats concrets', about_market: 'Adapté au marché africain', about_delivery: 'Livraison rapide', about_quality: 'Qualité premium',
    about_timeline_2022: 'Les débuts', about_timeline_2023: 'Premières applications métier', about_timeline_2024: 'AKATech Agence', about_timeline_2025: "Aujourd'hui",
    project_type: 'Type', project_market: 'Marché', project_role: 'Mon rôle', project_year: 'Année', project_view: 'Voir le projet', project_demo: 'Démo locale', project_progress: 'En cours',
    service_cta: 'Demander un devis', service_delay: 'Délai', service_hero_kicker: 'De la consultation au déploiement', service_hero_text: 'chaque service est conçu pour répondre aux réalités du marché ivoirien — rapide, efficace, rentable.',
    pricing_kicker: 'Pas de frais cachés. Pas de jargon.', pricing_tab_title: 'CHOISISSEZ VOTRE FORMULE IDÉALE', pricing_order: 'Commander →', pricing_popular: 'LE PLUS POPULAIRE', pricing_urgency: '2 créneaux disponibles', pricing_urgency_text: 'ce mois-ci — les projets sont traités dans l\'ordre d\'arrivée.',
    blogHero: 'Stratégie digitale, développement web, SEO et e-commerce — des contenus concrets pour les entrepreneurs ivoiriens.', blogTitle: 'Insights & conseils pour votre business digital',
    contactHero: "Devis gratuit en moins de 24h. Pas d'engagement, pas de jargon technique — juste une conversation pour comprendre votre besoin.", contactTitle: 'Parlons de votre projet',
    domainesTitle: 'Ce que AKATech Studio concoit pour vous',
    domainesIntro: 'De la vitrine au SaaS, nous concevons des experiences digitales utiles, claires et memorables.',
    domainesCta: "Votre projet ne rentre dans aucune case ? On s'adapte.",
    discussProject: 'Discuter de mon projet',
    assistantTitle: 'ASSISTANT AKATECH', assistantLive: 'Répond en direct', assistantPlaceholder: 'Décrivez votre projet…',
    assistantMessage: 'Votre message', send: 'Envoyer', quoteQuestionnaire: 'Questionnaire de devis',
    assistantGreeting: 'Bonjour ! Je suis l’assistant AKATech. Décrivez votre projet et je vous orienterai vers la meilleure solution.',
    quoteTitle: 'Questionnaire de devis', quoteMissing: 'Type de devis introuvable', quoteMissingText: 'Le type de questionnaire demandé n’existe pas. Vérifiez le lien ou choisissez une option valide.',
    quoteIntro: 'Répondez simplement aux questions ci-dessous. Vos réponses aideront Aka à comprendre votre projet et à préparer une proposition adaptée.',
    invalidToken: 'Ce formulaire est protégé par un token de sécurité. Le lien du questionnaire est invalide ou incomplet.',
    estimatedQuote: 'Devis estimé', acceptQuote: 'J’accepte le devis', declineQuote: 'Je refuse le devis', saving: 'Enregistrement…',
    submitQuestionnaire: 'Soumettre le questionnaire', submitting: 'Soumission…', loadingQuestionnaire: 'Chargement du questionnaire…',
    homeSlogan1: 'Un site qui travaille pour vous', homeHighlight1: '24h/24',
    homeSlogan2: 'Attirez des clients, gagnez en', homeHighlight2: 'crédibilité',
    homeSlogan3: 'Développez votre activité', homeHighlight3: 'sereinement',
    homeHeroText: 'Lancez un site professionnel qui inspire confiance et déclenche des demandes.',
    homeServicesTitle: 'NOS prestations.', processTitle: "De l'idée à la mise en ligne",
    processLabel: 'Notre processus', projectsTitle: 'Nos dernières réalisations',
    projectsHint: '— glissez pour naviguer',
    pricingLead: 'Des formules claires, adaptées aux besoins des petites structures et freelances — comparez et choisissez.',
  },
  en: {
    home: 'Home', about: 'About', services: 'Services', projects: 'Projects',
    pricing: 'Pricing', blog: 'Blog', contact: 'Contact', explorer: 'Explore',
    startProject: 'START MY PROJECT', backToSite: 'Back to site',
    ourProjects: 'Our work', studio: 'The Studio.', portfolio: 'Portfolio',
    selectedProjects: 'Selected projects', transparentQuotes: 'Transparent quotes',
    adviceNews: 'Advice & news', service: 'Services', whatWeOffer: 'What we offer',
    aboutTeam: 'Our team, Abidjan', talkProject: "Let's discuss your project",
    darkMode: 'Dark mode', lightMode: 'Light mode', language: 'Language',
    menu: 'Menu', close: 'Close', homeAria: 'Back to home',
    freeQuote: 'Free quote', viewServices: 'View services', chooseSolution: 'Choose your solution',
    service_site_vitrine: 'Website Design', service_cartes_dashboards: 'Interactive Maps & Dashboards',
    service_maintenance: 'Maintenance & Support', service_google_my_business: 'Google Business Profile',
    service_chatbot_ia: 'AI Chatbot Integration', service_paiement_en_ligne: 'Online Payment Integration',
    servicesHero: 'From consultation to deployment, every service is designed for the realities of the Ivorian market.',
    projectsHero: 'Showcase websites, e-commerce, SaaS and portfolios: every project tells a story of successful digital transformation.',
    deliveredProjects: 'projects delivered', satisfied: 'satisfied', online: 'live', inProgress: 'In progress',
    pricingHero: 'Fair prices adapted to the African market, with a free quote and no commitment.', pricingTitle: 'Clear offers for every stage.',
    aboutHero: 'AKATech helps entrepreneurs and SMEs in Côte d’Ivoire build a serious digital presence.', aboutTitle: 'Your digital growth is our mission.',
    about_results: 'Concrete results', about_market: 'Built for the African market', about_delivery: 'Fast delivery', about_quality: 'Premium quality',
    about_timeline_2022: 'The beginnings', about_timeline_2023: 'First business apps', about_timeline_2024: 'AKATech Agency', about_timeline_2025: 'Today',
    project_type: 'Type', project_market: 'Market', project_role: 'My role', project_year: 'Year', project_view: 'View project', project_demo: 'Local demo', project_progress: 'In progress',
    service_cta: 'Request a quote', service_delay: 'Lead time', service_hero_kicker: 'From consultation to deployment', service_hero_text: 'each service is designed for the realities of the Ivorian market — fast, efficient, and profitable.',
    pricing_kicker: 'No hidden fees. No jargon.', pricing_tab_title: 'CHOOSE YOUR IDEAL FORMULA', pricing_order: 'Order →', pricing_popular: 'MOST POPULAR', pricing_urgency: '2 slots available', pricing_urgency_text: 'this month — projects are handled in order of arrival.',
    blogHero: 'Digital strategy, web development, SEO and e-commerce: practical content for entrepreneurs in Côte d’Ivoire.', blogTitle: 'Insights and advice for your digital business',
    contactHero: 'Free quote within 24 hours. No commitment, no technical jargon: just a conversation to understand your needs.', contactTitle: 'Let’s discuss your project',
    domainesTitle: 'What AKATech Studio designs for you',
    domainesIntro: 'From showcase websites to SaaS, we design useful, clear and memorable digital experiences.',
    domainesCta: 'Does your project fit no category? We adapt.',
    discussProject: 'Discuss my project',
    assistantTitle: 'AKATECH ASSISTANT', assistantLive: 'Live replies', assistantPlaceholder: 'Describe your project…',
    assistantMessage: 'Your message', send: 'Send', quoteQuestionnaire: 'Quote questionnaire',
    assistantGreeting: 'Hello! I am the AKATech assistant. Describe your project and I will guide you toward the best solution.',
    quoteTitle: 'Quote questionnaire', quoteMissing: 'Quote type not found', quoteMissingText: 'This questionnaire type does not exist. Check the link or choose a valid option.',
    quoteIntro: 'Answer the questions below. Your answers will help Aka understand your project and prepare a tailored proposal.',
    invalidToken: 'This form is protected by a security token. The questionnaire link is invalid or incomplete.',
    estimatedQuote: 'Estimated quote', acceptQuote: 'I accept the quote', declineQuote: 'I decline the quote', saving: 'Saving…',
    submitQuestionnaire: 'Submit questionnaire', submitting: 'Submitting…', loadingQuestionnaire: 'Loading questionnaire…',
    homeSlogan1: 'A website that works for you', homeHighlight1: '24/7',
    homeSlogan2: 'Attract customers, build', homeHighlight2: 'credibility',
    homeSlogan3: 'Grow your business', homeHighlight3: 'with confidence',
    homeHeroText: 'Launch a professional website that builds trust and generates enquiries.',
    homeServicesTitle: 'OUR services.', processTitle: 'From idea to launch',
    processLabel: 'Our process', projectsTitle: 'Our latest work',
    projectsHint: '— swipe to browse',
    pricingLead: 'Clear packages tailored to small businesses and freelancers — compare and choose.',
  },
  es: {
    home: 'Inicio', about: 'Nosotros', services: 'Servicios', projects: 'Proyectos',
    pricing: 'Precios', blog: 'Blog', contact: 'Contacto', explorer: 'Explorar',
    startProject: 'INICIAR MI PROYECTO', backToSite: 'Volver al sitio',
    ourProjects: 'Nuestros proyectos', studio: 'El Estudio.', portfolio: 'Portafolio',
    selectedProjects: 'Proyectos seleccionados', transparentQuotes: 'Presupuestos claros',
    adviceNews: 'Consejos y noticias', service: 'Servicio', whatWeOffer: 'Lo que ofrecemos',
    aboutTeam: 'Nuestro equipo, Abiyán', talkProject: 'Hablemos de tu proyecto',
    darkMode: 'Modo oscuro', lightMode: 'Modo claro', language: 'Idioma',
    menu: 'Menu', close: 'Cerrar', homeAria: 'Volver al inicio',
    freeQuote: 'Presupuesto gratis', viewServices: 'Ver servicios', chooseSolution: 'Elige tu solución',
    service_site_vitrine: 'Diseño de sitios web', service_cartes_dashboards: 'Mapas interactivos y dashboards',
    service_maintenance: 'Mantenimiento y soporte', service_google_my_business: 'Perfil de Empresa de Google',
    service_chatbot_ia: 'Integración de chatbot IA', service_paiement_en_ligne: 'Integración de pagos online',
    servicesHero: 'Desde la consulta hasta el lanzamiento, cada servicio responde a las realidades del mercado marfileño.',
    projectsHero: 'Sitios web, comercio electrónico, SaaS y portafolios: cada proyecto cuenta una historia de transformación digital exitosa.',
    deliveredProjects: 'proyectos entregados', satisfied: 'satisfechos', online: 'en línea', inProgress: 'En curso',
    pricingHero: 'Precios honestos adaptados al mercado africano, con presupuesto gratuito y sin compromiso.', pricingTitle: 'Ofertas claras para cada etapa.',
    aboutHero: 'AKATech acompaña a emprendedores y pymes en Costa de Marfil que buscan una presencia digital sólida.', aboutTitle: 'Tu crecimiento digital es nuestra misión.',
    about_results: 'Resultados concretos', about_market: 'Adaptado al mercado africano', about_delivery: 'Entrega rápida', about_quality: 'Calidad premium',
    about_timeline_2022: 'Los inicios', about_timeline_2023: 'Primeras aplicaciones empresariales', about_timeline_2024: 'Agencia AKATech', about_timeline_2025: 'Hoy',
    project_type: 'Tipo', project_market: 'Mercado', project_role: 'Mi rol', project_year: 'Año', project_view: 'Ver proyecto', project_demo: 'Demo local', project_progress: 'En curso',
    service_cta: 'Solicitar un presupuesto', service_delay: 'Plazo', service_hero_kicker: 'Desde la consulta hasta el lanzamiento', service_hero_text: 'cada servicio está pensado para responder a las realidades del mercado marfileño — rápido, eficiente y rentable.',
    pricing_kicker: 'Sin gastos ocultos. Sin jerga.', pricing_tab_title: 'ELIGE TU FÓRMULA IDEAL', pricing_order: 'Pedir →', pricing_popular: 'MÁS POPULAR', pricing_urgency: '2 plazas disponibles', pricing_urgency_text: 'este mes — los proyectos se gestionan por orden de llegada.',
    blogHero: 'Estrategia digital, desarrollo web, SEO y comercio electrónico: contenido práctico para emprendedores marfileños.', blogTitle: 'Ideas y consejos para tu negocio digital',
    contactHero: 'Presupuesto gratuito en menos de 24 horas. Sin compromiso ni jerga técnica: solo una conversación para entender tu necesidad.', contactTitle: 'Hablemos de tu proyecto',
    domainesTitle: 'Lo que AKATech Studio crea para ti',
    domainesIntro: 'Desde sitios vitrina hasta SaaS, creamos experiencias digitales utiles, claras y memorables.',
    domainesCta: '¿Tu proyecto no encaja en ninguna categoria? Nos adaptamos.',
    discussProject: 'Hablar de mi proyecto',
    assistantTitle: 'ASISTENTE AKATECH', assistantLive: 'Respuestas en directo', assistantPlaceholder: 'Describe tu proyecto…',
    assistantMessage: 'Tu mensaje', send: 'Enviar', quoteQuestionnaire: 'Cuestionario de presupuesto',
    assistantGreeting: '¡Hola! Soy el asistente de AKATech. Describe tu proyecto y te orientaré hacia la mejor solución.',
    quoteTitle: 'Cuestionario de presupuesto', quoteMissing: 'Tipo de presupuesto no encontrado', quoteMissingText: 'Este tipo de cuestionario no existe. Comprueba el enlace o elige una opción válida.',
    quoteIntro: 'Responde a las preguntas. Tus respuestas ayudarán a Aka a entender tu proyecto y preparar una propuesta adaptada.',
    invalidToken: 'Este formulario está protegido por un token de seguridad. El enlace no es válido o está incompleto.',
    estimatedQuote: 'Presupuesto estimado', acceptQuote: 'Acepto el presupuesto', declineQuote: 'Rechazo el presupuesto', saving: 'Guardando…',
    submitQuestionnaire: 'Enviar cuestionario', submitting: 'Enviando…', loadingQuestionnaire: 'Cargando cuestionario…',
    homeSlogan1: 'Un sitio web que trabaja para ti', homeHighlight1: '24/7',
    homeSlogan2: 'Atrae clientes y gana', homeHighlight2: 'credibilidad',
    homeSlogan3: 'Haz crecer tu negocio', homeHighlight3: 'con confianza',
    homeHeroText: 'Lanza un sitio web profesional que inspire confianza y genere solicitudes.',
    homeServicesTitle: 'NUESTROS servicios.', processTitle: 'De la idea al lanzamiento',
    processLabel: 'Nuestro proceso', projectsTitle: 'Nuestros últimos proyectos',
    projectsHint: '— desliza para navegar',
    pricingLead: 'Paquetes claros para pequeñas empresas y freelancers — compara y elige.',
  },
}

const LanguageCtx = createContext({ language: 'fr', setLanguage: () => {}, t: key => TRANSLATIONS.fr[key] || key })

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('fr')

  useEffect(() => {
    const saved = window.localStorage.getItem('akatech-language')
    if (TRANSLATIONS[saved]) setLanguage(saved)
  }, [])

  useEffect(() => {
    document.documentElement.lang = language
    window.localStorage.setItem('akatech-language', language)
  }, [language])

  const t = key => TRANSLATIONS[language][key] || TRANSLATIONS.fr[key] || key

  return <LanguageCtx.Provider value={{ language, setLanguage, t }}>{children}</LanguageCtx.Provider>
}

export const useLanguage = () => useContext(LanguageCtx)
