'use client'
import { createContext, useContext } from 'react'

/* Le site est écrit uniquement en français.
   La traduction dans une autre langue est assurée par le bouton de langue
   (components/layout/LanguageToggle.jsx), qui utilise la traduction Google
   du navigateur — plus de dictionnaires EN/ES à maintenir. */
const TRANSLATIONS = {
  fr: {
    uiClose: 'Fermer', uiBackHome: "Retour à l'accueil", uiStartProject: 'Démarrer un projet', uiFreeQuote24: 'Devis gratuit · Réponse en moins de 24h', uiExploreMode: 'Mode Explorer', uiYear: 'Année', uiMarket: 'Marché', uiCountry: "Côte d'Ivoire", uiStatus: 'Statut', uiSlideHint: 'Glissez pour tourner le globe · Cliquez sur un projet pour le découvrir', uiStack: 'Notre stack · Nos avantages · Nos performances', uiStartMyProject: 'Démarrer mon projet', uiScroll: 'Défilez', uiSearch: 'Rechercher...', uiNoResults: 'Aucun résultat trouvé.', uiReadArticle: "Lire l'article", uiSubscribe: "S'abonner", uiTopics: 'Sujets', tickerSevenDays: '7 jours', tickerSlots: '3 créneaux', tickerSlotsPost: ' dispo ce mois', tickerLead: 'Délai moyen', tickerReply: 'Réponse en', tickerReplyPost: 'moins de 2h', badgeDelivery: 'Livraison 5-7 jours', badgeDesign: 'Design sur mesure', badgeSeo: 'SEO intégré', badgeSupport: 'Support 48h', badgeHosting: 'Hébergement offert', metricLighthouse: 'Score Lighthouse', metricLoad: 'Chargement moyen', metricResponsive: 'Responsive', metricSeo: 'Optimisé dès le code', metricSsl: 'Gratuit inclus',
    home: 'Accueil', about: 'À propos', services: 'Services', projects: 'Réalisation',
    pricing: 'Tarifs', blog: 'Blog', contact: 'Contact', explorer: 'Explorer',
    startProject: 'DEMARRER MON PROJET', backToSite: 'Retour au site',
    ourProjects: 'Nos realisations', studio: 'Le Studio.', portfolio: 'Portfolio',
    selectedProjects: 'Projets selectionnes', transparentQuotes: 'Devis transparents',
    adviceNews: 'Conseils & actualites', service: 'Service', whatWeOffer: 'Ce que nous proposons',
    aboutTeam: 'Notre equipe, Abidjan', talkProject: 'Parlons de ton projet',
    darkMode: 'Mode sombre', lightMode: 'Mode clair', language: 'Langue',
    menu: 'Menu', close: 'Fermer', homeAria: "Retour a l'accueil",
    freeQuote: 'Devis gratuit', viewServices: 'Voir les services', chooseSolution: 'Choisissez votre solution',
    service_site_vitrine: 'Conception de Site Web', service_cartes_dashboards: 'Cartes Interactives & Dashboards', service_ecommerce: 'E-commerce', service_application_web: 'Application Web / SaaS',
    service_maintenance: 'Maintenance & Support', service_google_my_business: 'Fiche Google My Business',
    service_chatbot_ia: 'Intégration IA Chatbot', service_paiement_en_ligne: 'Intégration de Paiement en Ligne', service_other: 'Autre',
    service_site_vitrine_tagline: 'Votre présence en ligne professionnelle.', service_cartes_dashboards_tagline: 'Visualisez vos données avec puissance.', service_maintenance_tagline: 'Votre projet sécurisé et toujours performant.', service_google_my_business_tagline: 'Soyez visible sur Google Maps et la recherche locale.', service_chatbot_ia_tagline: 'Le même assistant conversationnel que sur akatech.vercel.app.', service_paiement_en_ligne_tagline: 'Encaissez directement depuis votre site.',
    service_site_vitrine_b1: 'Site vitrine moderne', service_site_vitrine_b1_d: 'Design attractif et performant.', service_site_vitrine_b2: 'Boutique e-commerce', service_site_vitrine_b2_d: 'Vendez vos produits en ligne.', service_site_vitrine_b3: 'Portfolio créatif', service_site_vitrine_b3_d: 'Mettez en valeur vos réalisations.', service_site_vitrine_b4: 'Application SaaS sur mesure', service_site_vitrine_b4_d: 'Solutions adaptées à vos besoins.', service_site_vitrine_b5: 'Design responsive', service_site_vitrine_b5_d: 'Parfait sur tous les écrans.', service_site_vitrine_b6: 'Optimisation SEO', service_site_vitrine_b6_d: 'Soyez visible, soyez choisi.',
    service_dashboard_b1: 'Cartes Mapbox interactives', service_dashboard_b1_d: 'Explorez vos données en temps réel.', service_dashboard_b2: 'Géolocalisation avancée', service_dashboard_b2_d: 'Suivi précis et analyse spatiale.', service_dashboard_b3: 'Dashboards analytiques', service_dashboard_b3_d: 'Indicateurs clés et visualisations claires.', service_dashboard_b4: 'Données temps réel', service_dashboard_b4_d: 'Toujours à jour pour de meilleures décisions.', service_dashboard_b5: 'Rapports personnalisés', service_dashboard_b5_d: 'Sur mesure selon vos besoins.',
    service_maintenance_b1: 'Sauvegardes automatiques', service_maintenance_b1_d: 'Vos données sont protégées en continu.', service_maintenance_b2: 'Mises à jour régulières', service_maintenance_b2_d: 'Plus de sécurité et de stabilité.', service_maintenance_b3: 'Surveillance 24h/24', service_maintenance_b3_d: 'Monitoring temps réel, incidents anticipés.', service_maintenance_b4: 'Support WhatsApp', service_maintenance_b4_d: 'Une assistance rapide et à portée de main.', service_maintenance_b5: 'Assistance rapide', service_maintenance_b5_d: 'Notre équipe réactive pour vos problèmes.',
    service_gmb_b1: 'Optimisation complète', service_gmb_b1_d: 'NAP, catégories, description, photos et services.', service_gmb_b2: 'Gestion des avis', service_gmb_b2_d: 'Réponses rapides pour votre e-réputation.', service_gmb_b3: 'Publications régulières', service_gmb_b3_d: 'Actualités, offres et événements.', service_gmb_b4: 'Suivi des performances', service_gmb_b4_d: 'Statistiques claires pour mesurer vos résultats.', service_gmb_b5: 'Plus de visibilité', service_gmb_b5_d: 'Attirez plus de clients locaux chaque mois.',
    service_chatbot_b1: 'Assistant sur-mesure', service_chatbot_b1_d: 'Formé sur votre activité, vos services et vos tarifs.', service_chatbot_b2: 'Qualification automatique', service_chatbot_b2_d: 'Comprend le besoin du visiteur avant de le transmettre.', service_chatbot_b3: 'Disponible 24h/24', service_chatbot_b3_d: 'Répond même quand vous êtes indisponible.', service_chatbot_b4: 'Capture de leads', service_chatbot_b4_d: 'Nom, contact et besoin enregistrés automatiquement.', service_chatbot_b5: 'Intégration WhatsApp', service_chatbot_b5_d: 'Relais possible vers votre WhatsApp Business.',
    service_payment_b1: 'Mobile Money', service_payment_b1_d: 'Orange Money, MTN MoMo, Wave.', service_payment_b2: 'Carte bancaire', service_payment_b2_d: 'Selon vos besoins et votre clientèle.', service_payment_b3: 'Suivi des transactions', service_payment_b3_d: 'Historique clair de chaque paiement.', service_payment_b4: 'Notifications automatiques', service_payment_b4_d: 'Vous et votre client êtes informés en temps réel.', service_payment_b5: 'Flux sécurisés', service_payment_b5_d: 'Paiements protégés de bout en bout.',
    pricing_from_150k: 'À partir de 150 000 FCFA', pricing_from_20000_month: 'À partir de 20 000 FCFA/mois', pricing_from_10000_month: 'À partir de 10 000 FCFA/mois', pricing_quote: 'Sur devis', pricing_scroll: 'Scroll',
    stats_sub_concept: 'Du concept au déploiement', stats_sub_delivery: 'Livrés dans les délais', stats_sub_market: 'Startups, PME, créatifs', stats_sub_web: 'En développement web',
    domaines_site_vitrine: 'Sites vitrines & sites métier', domaines_ecommerce: 'E-commerce', domaines_reservation: 'Réservation & rendez-vous', domaines_site_vitrine_desc: 'Pour présenter votre activité et transformer vos visiteurs en clients : entreprise, agence, cabinet, école, pressing, salon, restaurant, portfolio professionnel.', domaines_ecommerce_desc: 'Pour vendre vos produits directement en ligne : catalogue, panier, paiement Mobile Money, livraison, gestion des stocks, tableau de bord vendeur.', domaines_reservation_desc: 'Pour permettre à vos clients de réserver sans vous appeler : résidences, hôtels, salons, restaurants, prestations, location de véhicules, salles.', domaines_plateforme_desc: 'Pour une vraie plateforme multi-utilisateurs : comptes clients/vendeurs, géolocalisation, KYC, paiements répartis, dashboards.', domaines_facturation_desc: 'Pour digitaliser la gestion quotidienne de votre activité : devis, factures avec TVA et numérotation automatique, clients, historique des ventes, export PDF.', domaines_applications_desc: 'Pour automatiser un processus propre à votre entreprise : dashboard métier, CRM, gestion de stocks, suivi logistique, portail client, SaaS sur-mesure.', domaines_pos_desc: "Système d'encaissement et de caisse physique — bientôt disponible.",
    domaines_plateforme: 'Plateformes & marketplaces', domaines_facturation: 'Gestion commerciale & facturation', domaines_applications: 'Applications web & outils métier', domaines_pos: 'POS & caisse',
    process_brief: 'Brief & découverte', process_devis: 'Devis & contrat', process_acompte: 'Acompte & contenus', process_conception: 'Conception & développement', process_validation: 'Prévisualisation & validation', process_livraison: 'Livraison & suivi',
    process_sub_brief: 'On vous écoute', process_sub_devis: 'Périmètre, prix, délai', process_sub_acompte: '50% pour lancer le projet', process_sub_conception: 'Design 100% sur mesure', process_sub_validation: 'Vous testez avant de payer', process_sub_livraison: 'En ligne, avec support',
    process_desc_brief: 'Nous échangeons sur votre projet, vos objectifs et vos besoins. Premier échange gratuit et sans engagement.', process_desc_devis: 'Nous définissons le périmètre, le prix et le délai, puis validons le projet ensemble.', process_desc_acompte: 'Vous versez 50% d’acompte et transmettez logo, informations et visuels — le délai démarre à réception.', process_desc_conception: 'Nous concevons et développons votre projet conformément au devis validé.', process_desc_validation: 'Vous recevez un lien de prévisualisation, testez le projet et nous effectuons les corrections mineures incluses.', process_desc_livraison: 'Après le solde, le projet est mis en ligne et les accès transmis — la garantie et le support démarrent ensuite.',
    service_site_vitrine_desc: 'Création de sites web modernes, responsive et optimisés pour convertir vos visiteurs en clients. Du portfolio à la plateforme e-commerce.', service_cartes_dashboards_desc: 'Intégration de cartes Mapbox / Leaflet et de dashboards de visualisation de données. Vos données brutes deviennent des interfaces actionnables.', service_maintenance_desc: 'Suivi technique, corrections de bugs, mises à jour de sécurité et améliorations continues. Vous vous concentrez sur votre métier.', service_google_my_business_desc: 'Création ou optimisation de votre fiche Google (NAP, photos, SEO local) et suivi mensuel : avis, publications et statistiques.', service_chatbot_ia_desc: 'Un chatbot conversationnel intégré à votre site pour interagir avec vos visiteurs et les guider — le même type d’assistant que celui d’akatech.vercel.app, pensé pour augmenter la productivité de votre business.', service_paiement_en_ligne_desc: 'Intégration de solutions de paiement directement sur votre site — Mobile Money (Orange Money, MTN MoMo, Wave) et carte bancaire selon vos besoins — pour encaisser sans friction.',
    hero_copy_intro: 'On convertit, vous', hero_copy_goal: 'encaissez.', stats_projects_label: 'Projets livrés', stats_clients_label: 'Clients satisfaits', stats_support_label: 'Clients accompagnés', stats_experience_label: "Années d'expérience",
    testimonials_title: 'Ce que disent nos clients', projects_latest_title: 'Nos dernières réalisations', projects_hint: '— glissez pour naviguer',
    servicesHero: 'De la consultation au déploiement, chaque service est conçu pour répondre aux réalités du marché ivoirien.',
    projectsHero: 'Sites vitrines, e-commerces, SaaS, portfolios… Chaque réalisation est une histoire de transformation digitale réussie.',
    deliveredProjects: 'réalisations livrées', satisfied: 'satisfaits', online: 'en ligne', inProgress: 'En cours',
    pricingHero: 'Des prix honnêtes adaptés au marché africain, avec devis gratuit et sans engagement.', pricingTitle: 'Des offres claires, pour chaque étape.',
    aboutHero: "AKATech accompagne les entrepreneurs et PME en Côte d'Ivoire qui veulent une présence digitale sérieuse.", aboutTitle: "Votre croissance digitale, c'est notre mission.",
    aboutMission: 'MISSION & VISION', aboutEvolution: "L'ÉVOLUTION D'AKATECH", aboutDistinct: 'CE QUI NOUS DISTINGUE', aboutTech: 'LES TECHNOLOGIES QUI FONT LA DIFFÉRENCE', about_results: 'Résultats concrets', about_market: 'Adapté au marché africain', about_delivery: 'Livraison rapide', about_quality: 'Qualité premium', about_results_desc: 'Chaque solution est conçue pour générer des résultats mesurables : plus de clients, plus de revenus, moins de tâches manuelles.', about_market_desc: 'Je comprends les réalités locales — Mobile Money, coupures internet et faible débit. Vos solutions fonctionnent dans votre contexte.', about_delivery_desc: 'Pas d’attente de 3 mois. Les projets sont livrés en 5 à 21 jours selon la complexité, avec des jalons clairs à chaque étape.', about_quality_desc: 'Code propre, design sur-mesure et animations soignées. Chaque détail compte pour que votre solution se démarque.', about_timeline_2022_desc: "Premier projet freelance livré : un site vitrine pour un commerçant abidjanais. Le début d’une aventure.", about_timeline_2023_desc: 'Développement de LivreurTrack Pro et MonCashJour, des outils pensés pour les commerçants et livreurs locaux.', about_timeline_2024_desc: 'Transformation en agence officielle. Lancement de services structurés et premiers clients récurrents.', about_timeline_2025_desc: '{count} projets livrés, 100% de clients satisfaits. Le Studio. continue de grandir et d’innover.',
    about_timeline_2022: 'Les débuts', about_timeline_2023: 'Premières applications métier', about_timeline_2024: 'AKATech Agence', about_timeline_2025: "Aujourd'hui",
    project_type: 'Type', project_market: 'Marché', project_role: 'Mon rôle', project_year: 'Année', project_view: 'Voir le projet', project_demo: 'Démo locale', project_progress: 'En cours', project_country: "Côte d'Ivoire", project_design: 'Conception & Développement', projectsTitleUpper: 'RÉALISATIONS', projectsScrollHint: 'Défilez pour parcourir', projectsCountHeading: '{count} réalisations, une par une.', projectsCtaTitle: 'VOTRE PROJET, NOTRE PROCHAIN SUCCÈS ?', projectsCtaLead: 'Votre projet,', projectsCtaHighlight: 'notre prochain succès ?', projectsIntro: 'Ci-dessous : des projets réalisés pour des PME, startups et créateurs. Découvrez les objectifs, technologies et résultats de chaque réalisation sur mesure.', caseProblem: 'Problème', caseSolution: 'Solution', caseResult: 'Résultat', status: 'Statut', projectsSwipeHint: 'Glissez pour naviguer', projectPrevAria: 'Projet précédent', projectNextAria: 'Projet suivant',
    service_cta: 'Demander un devis', service_delay: 'Délai', service_hero_kicker: 'De la consultation au déploiement', service_hero_text: 'chaque service est conçu pour répondre aux réalités du marché ivoirien — rapide, efficace, rentable.',
    pricing_kicker: 'Pas de frais cachés. Pas de jargon.', pricing_tab_title: 'CHOISISSEZ VOTRE FORMULE IDÉALE', pricing_order: 'Commander →', pricing_popular: 'LE PLUS POPULAIRE', pricing_urgency: '2 créneaux disponibles', pricing_urgency_text: 'ce mois-ci — les projets sont traités dans l\'ordre d\'arrivée.',
    blogHero: 'Stratégie digitale, développement web, SEO et e-commerce — des contenus concrets pour les entrepreneurs ivoiriens.', blogTitle: 'Insights & conseils pour votre business digital', backToBlog: 'Retour au blog', readingTime: 'de lecture', founderLabel: 'Founder, AKATech', followLinkedIn: 'Suivre sur LinkedIn', relatedArticles: 'Articles similaires', readArticle: 'Lire',
    contactHero: "Devis gratuit en moins de 24h. Pas d'engagement, pas de jargon technique — juste une conversation pour comprendre votre besoin.", contactTitle: 'Parlons de votre projet',
    contactChannelsTitle: 'Comment nous contacter', contactChannelsIntro: 'Choisissez le canal qui vous convient. WhatsApp est le plus rapide — on répond en moins de 2h.', contactWhatsApp: 'WhatsApp', contactEmail: 'Email', contactPhone: 'Téléphone', contactLocation: 'Localisation', contactResponseFast: 'Réponse en moins de 2h', contactResponse24h: 'Réponse sous 24h', contactOpenHours: 'Lun–Ven, 8h–18h', contactMovePossible: 'Déplacements possibles', contactSocials: 'Réseaux sociaux', contactSelectChannel: 'Choisissez le canal',
    domainesTitle: 'Ce que AKATech Studio concoit pour vous',
    domainesIntro: 'De la vitrine au SaaS, nous concevons des experiences digitales utiles, claires et memorables.',
    domainesCta: "Votre projet ne rentre dans aucune case ? On s'adapte.",
    discussProject: 'Discuter de mon projet',
    assistantTitle: 'ASSISTANT AKATECH', assistantLive: 'Répond en direct', assistantPlaceholder: 'Décrivez votre projet…',
    assistantMessage: 'Votre message', send: 'Envoyer', quoteQuestionnaire: 'Questionnaire de devis',
    assistantGreeting: 'Bonjour ! Je suis l’assistant AKATech. Décrivez votre projet et je vous orienterai vers la meilleure solution.',
    quoteTitle: 'Questionnaire de devis', quoteMissing: 'Type de devis introuvable', quoteMissingText: 'Le type de questionnaire demandé n’existe pas. Vérifiez le lien ou choisissez une option valide.',
    quoteIntro: 'Répondez simplement aux questions ci-dessous. Vos réponses aideront Aka à comprendre votre projet et à préparer une proposition adaptée.',
    invalidToken: 'Ce formulaire est protégé par un token de sécurité. Le lien du questionnaire est invalide ou incomplet.',
    estimatedQuote: 'Devis estimé', acceptQuote: 'J’accepte le devis', declineQuote: 'Je refuse le devis', saving: 'Enregistrement…',
    submitQuestionnaire: 'Soumettre le questionnaire', submitting: 'Soumission…', loadingQuestionnaire: 'Chargement du questionnaire…',
    homeSlogan1: 'Un site qui travaille pour vous', homeHighlight1: '24h/24',
    homeSlogan2: 'Attirez des clients, gagnez en', homeHighlight2: 'crédibilité',
    homeSlogan3: 'Développez votre activité', homeHighlight3: 'sereinement',
    heroTrust: 'Ils nous ont fait confiance', heroStartProject: 'Démarrer mon projet', heroBookCall: 'Prenez RDV', homeHeroText: 'Lancez un site professionnel qui inspire confiance et déclenche des demandes.', viewService: 'Voir le service', viewAllProjects: 'Voir tous les projets', homeProjectsUpper: 'NOS DERNIÈRES RÉALISATIONS', homeTestimonialsUpper: 'CE QUE DISENT NOS CLIENTS', faqUpper: 'QUESTIONS FRÉQUENTES', faqTitle: 'Questions fréquentes', geoUpper: 'OÙ INTERVENONS-NOUS ?', geoTitle: 'Où intervenons-nous ?', geoLead: 'Basés à Abidjan, on travaille 100% remote avec des clients partout en Afrique de l’Ouest et la diaspora.', geoBadgeRemote: '100% remote', geoBadgeChannels: 'WhatsApp & Zoom', geoBadgeRealtime: 'Suivi en temps réel', geoBadgeCurrencies: 'FCFA & EUR', formUpper: 'DÉCRIVEZ VOTRE PROJET', formTitle: 'Décrivez votre projet', formLead: 'Remplissez le formulaire — on vous recontacte par email sous 24h avec un devis gratuit.', receiveQuote: 'Recevoir mon devis en 24h', sendAnother: 'Envoyer un autre message', writeUs: 'Nous écrire', formSuccess: 'Votre demande a bien été reçue. On répond en moins de 24h directement par email — à très vite !', formRequired: 'Merci de renseigner au moins votre nom, votre email et votre besoin.', formErrorGeneric: 'Une erreur est survenue. Réessayez ou contactez-nous sur WhatsApp.', formPhoneLabel: 'WhatsApp / Tél', formProjectTypeLabel: 'Type de projet', formNeedLabel: 'Votre besoin en une phrase', projectTypeLabel: 'Type de projet', chooseLabel: 'Choisir...', privacyNote: 'Vos données restent confidentielles. Aucun spam.', messageSent: 'Message envoyé !',
    formBudgetLabel: 'Budget estimé', comingSoon: 'Bientôt en ligne', yourName: 'Votre nom', yourNeed: 'Votre besoin en une phrase',
    homeServicesTitle: 'NOS prestations.', processTitle: "De l'idée à la mise en ligne",
    processLabel: 'Notre processus', projectsTitle: 'Nos dernières réalisations',
    projectsHint: '— glissez pour naviguer',
    pricingLead: 'Des formules claires, adaptées aux besoins des petites structures et freelances — comparez et choisissez.',
    footerSlogan1: 'Un site pensé pour faire grandir votre activité.', footerSlogan2: 'Votre croissance commence en ligne.',
    footerSlogan3: 'Transformez votre présence en opportunités.', footerSlogan4: 'Digital, local, rentable.',
    askAiHeading: "Demandez à l'IA ce qu'elle pense d'AKATech",
    askAiPrompt: "Tu es un analyste indépendant. Consulte les informations publiques disponibles sur AKATech (akatech.vercel.app), agence web basée à Abidjan et fondée par Elvis Aka. Évalue honnêtement son positionnement, la qualité observable de ses réalisations, les clients qu'elle semble réellement servir, ses points forts, ses limites et les risques à vérifier avant de lui confier un site ou une application sur mesure. Distingue clairement les faits vérifiés, les indices et les inconnues. Termine par une recommandation nuancée pour une PME ouest-africaine.",
    copied: 'Copié !', askPlatform: 'Demander à',
    legal: 'Légal', legalMentions: 'Mentions légales', legalPrivacy: 'Confidentialité', legalTerms: "Conditions d'utilisation",
    explorerMode: 'Mode Explorer', explorerTitle: 'NOS PROJETS', viewSite: 'Voir le site', explorerHint: 'Faites défiler pour traverser le tunnel · Cliquez sur un projet pour le découvrir', explorerReducedMotion: 'Le tunnel 3D utilise un défilement immersif que votre système limite. Découvrez nos réalisations dans la vue classique.', explorerMobile: 'Le tunnel 3D est conçu pour le grand écran. Découvrez nos réalisations dans la vue classique.', viewProjects: 'Voir nos réalisations', online: 'En ligne', offline: 'Hors ligne', inProgressLabel: 'En cours', year: 'Année', market: 'Marché', status: 'Statut', backToSiteShort: 'Retour au site',
    footerServiceVitrine: 'Site Vitrine', footerServiceEcommerce: 'E-Commerce', footerServiceSaas: 'Application SaaS', footerServiceMaintenance: 'Maintenance',
    emailLabel: 'Email', sendMessageBtn: 'Envoyer un message',
    cookieHeading: 'On peut parler cookies deux secondes ?',
    cookieIntro: "Des cookies essentiels font tourner le site et nous permettent de mesurer la fréquentation de façon anonyme. Avec votre accord, on active aussi des cookies analytiques pour mieux comprendre votre navigation.",
    cookieEssentialTitle: 'Cookies essentiels', cookieEssentialDesc: 'Nécessaires au fonctionnement du site — toujours actifs.',
    cookieAnalyticsTitle: 'Cookies analytiques', cookieAnalyticsDesc: 'Nous aident à comprendre comment le site est utilisé.',
    acceptAll: 'Tout accepter', rejectOptional: 'Refuser les cookies optionnels',
    managePrefs: 'Gérer mes préférences', savePrefs: 'Enregistrer mes préférences', backBtn: '← Retour', backToHome: "Retour à l'accueil",
    cookieFooterText: "Vous pouvez changer d'avis à tout moment. Des questions sur vos données ? Écrivez à",
  },
}

const t = key => TRANSLATIONS.fr[key] || key

const LanguageCtx = createContext({ language: 'fr', t, tFr: t })

export function LanguageProvider({ children }) {
  return <LanguageCtx.Provider value={{ language: 'fr', t, tFr: t }}>{children}</LanguageCtx.Provider>
}

export const useLanguage = () => useContext(LanguageCtx)
export const VALID_LANGUAGES = ['fr']
