export const LEGAL_CONTENT = {
  mentions: {
    fr: { eyebrow: 'AKATech Studio · Informations légales', title: 'Mentions légales', intro: 'Cette page présente l’éditeur, l’hébergement et les règles d’utilisation des contenus publiés sur le site AKATech.', sections: [
      { title: 'Éditeur du site', blocks: [
        { type: 'text', text: 'Le site akatech.vercel.app est édité par AKATech Studio, activité de conception et de développement de solutions digitales basée à Abidjan, Côte d’Ivoire.' },
        { type: 'text', text: 'Responsable de la publication : M’Bollo Aka Elvis.' },
        { type: 'text', text: 'Contact : wthomasss06@gmail.com — +225 01 42 50 77 50.' },
        { type: 'text', text: 'Les informations d’identification administrative complémentaires de l’éditeur doivent être ajoutées dès qu’elles sont disponibles : forme juridique, numéro RCCM, identifiant fiscal et adresse professionnelle complète.' },
      ] },
      { title: 'Hébergement', blocks: [{ type: 'text', text: 'Le site est hébergé par Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, États-Unis. Le déploiement public est accessible à l’adresse akatech.vercel.app.' }] },
      { title: 'Activité', blocks: [
        { type: 'text', text: 'AKATech Studio propose notamment la conception de sites vitrines, de boutiques e-commerce, d’applications SaaS, d’API et de solutions backend, ainsi que des prestations de maintenance et de visibilité locale.' },
        { type: 'text', text: 'Les tarifs affichés ou communiqués par le parcours de devis sont des estimations. Une proposition commerciale ou un devis validé précise le périmètre, les livrables, les délais et les conditions applicables.' },
      ] },
      { title: 'Propriété intellectuelle', blocks: [
        { type: 'text', text: 'La structure, les textes, le design, les éléments graphiques, les composants logiciels et les contenus du site sont protégés par les règles applicables de propriété intellectuelle.' },
        { type: 'text', text: 'Toute reproduction, représentation, adaptation ou extraction non autorisée est interdite. Les marques, logos et contenus appartenant à des tiers restent la propriété de leurs titulaires.' },
      ] },
      { title: 'Contact et signalement', blocks: [{ type: 'text', text: 'Pour toute question relative au site ou pour signaler un contenu, contactez AKATech Studio à l’adresse wthomasss06@gmail.com.' }] },
    ] },
    en: { eyebrow: 'AKATech Studio · Legal information', title: 'Legal notice', intro: 'This page identifies the publisher, hosting provider and rules governing the content published on the AKATech website.', sections: [
      { title: 'Website publisher', blocks: [
        { type: 'text', text: 'The website akatech.vercel.app is published by AKATech Studio, a digital design and development activity based in Abidjan, Côte d’Ivoire.' },
        { type: 'text', text: 'Publication manager: M’Bollo Aka Elvis.' },
        { type: 'text', text: 'Contact: wthomasss06@gmail.com — +225 01 42 50 77 50.' },
        { type: 'text', text: 'Additional administrative identification details must be added when available: legal form, RCCM number, tax identification number and complete professional address.' },
      ] },
      { title: 'Hosting', blocks: [{ type: 'text', text: 'The website is hosted by Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, United States. The public deployment is available at akatech.vercel.app.' }] },
      { title: 'Business activity', blocks: [
        { type: 'text', text: 'AKATech Studio designs showcase websites, e-commerce stores, SaaS applications, APIs and backend solutions, and provides maintenance and local visibility services.' },
        { type: 'text', text: 'Prices displayed or communicated through the quote journey are estimates. A commercial proposal or approved quote defines the scope, deliverables, deadlines and applicable conditions.' },
      ] },
      { title: 'Intellectual property', blocks: [
        { type: 'text', text: 'The structure, copy, design, graphics, software components and content of this website are protected by applicable intellectual-property rules.' },
        { type: 'text', text: 'Unauthorised reproduction, representation, adaptation or extraction is prohibited. Third-party trademarks, logos and content remain the property of their respective owners.' },
      ] },
      { title: 'Contact and reporting', blocks: [{ type: 'text', text: 'For questions about the website or to report content, contact AKATech Studio at wthomasss06@gmail.com.' }] },
    ] },
    es: { eyebrow: 'AKATech Studio · Información legal', title: 'Aviso legal', intro: 'Esta página identifica al editor, al proveedor de alojamiento y las reglas aplicables al contenido publicado en el sitio de AKATech.', sections: [
      { title: 'Editor del sitio', blocks: [
        { type: 'text', text: 'El sitio akatech.vercel.app está publicado por AKATech Studio, actividad de diseño y desarrollo de soluciones digitales con sede en Abiyán, Costa de Marfil.' },
        { type: 'text', text: 'Responsable de la publicación: M’Bollo Aka Elvis.' },
        { type: 'text', text: 'Contacto: wthomasss06@gmail.com — +225 01 42 50 77 50.' },
        { type: 'text', text: 'Los datos administrativos complementarios del editor se añadirán cuando estén disponibles: forma jurídica, número RCCM, identificación fiscal y dirección profesional completa.' },
      ] },
      { title: 'Alojamiento', blocks: [{ type: 'text', text: 'El sitio está alojado por Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, Estados Unidos. El despliegue público está disponible en akatech.vercel.app.' }] },
      { title: 'Actividad', blocks: [
        { type: 'text', text: 'AKATech Studio diseña sitios web, tiendas de comercio electrónico, aplicaciones SaaS, APIs y soluciones backend, además de ofrecer mantenimiento y visibilidad local.' },
        { type: 'text', text: 'Los precios mostrados o comunicados durante el proceso de presupuesto son estimaciones. Una propuesta comercial o presupuesto aprobado define el alcance, los entregables, los plazos y las condiciones aplicables.' },
      ] },
      { title: 'Propiedad intelectual', blocks: [
        { type: 'text', text: 'La estructura, los textos, el diseño, los gráficos, los componentes de software y los contenidos del sitio están protegidos por las normas de propiedad intelectual aplicables.' },
        { type: 'text', text: 'Está prohibida toda reproducción, representación, adaptación o extracción no autorizada. Las marcas, logotipos y contenidos de terceros pertenecen a sus respectivos titulares.' },
      ] },
      { title: 'Contacto y denuncias', blocks: [{ type: 'text', text: 'Para cualquier pregunta sobre el sitio o para denunciar un contenido, escribe a AKATech Studio: wthomasss06@gmail.com.' }] },
    ] },
  },
  privacy: {
    fr: { eyebrow: 'AKATech Studio · Données personnelles', title: 'Politique de confidentialité', intro: 'AKATech Studio explique ici quelles données sont utilisées, pourquoi elles le sont et comment exercer vos droits.', sections: [
      { title: 'Responsable et contact', blocks: [{ type: 'text', text: 'Le responsable du traitement est AKATech Studio, basé à Abidjan, Côte d’Ivoire. Pour toute demande relative à vos données : wthomasss06@gmail.com.' }] },
      { title: 'Données collectées', blocks: [
        { type: 'text', text: 'Selon le parcours utilisé, le site peut traiter les données que vous saisissez volontairement : nom ou nom d’entreprise, adresse email, numéro de téléphone, type de projet, budget, délai, messages et réponses au questionnaire de devis.' },
        { type: 'text', text: 'Le site peut aussi recevoir des données techniques nécessaires à son fonctionnement : adresse IP ou empreinte technique limitée, navigateur, appareil, pages consultées, source de visite et identifiants de session.' },
        { type: 'text', text: 'Ne transmettez pas de données sensibles ou de documents confidentiels dans le chat ou les formulaires qui ne seraient pas nécessaires à votre demande.' },
      ] },
      { title: 'Finalités et bases d’utilisation', blocks: [
        { type: 'list', items: ['Répondre aux demandes envoyées via le formulaire de contact ou l’assistant IA.', 'Qualifier un besoin et générer un devis estimatif à partir des réponses fournies.', 'Conserver l’historique nécessaire au suivi commercial et à la sécurité du service.', 'Mesurer la fréquentation et améliorer la fiabilité du site, lorsque le consentement ou la base légale applicable le permet.'] },
        { type: 'text', text: 'Les données sont utilisées uniquement pour les finalités liées au service demandé, à la gestion de la relation avec le prospect ou au fonctionnement et à la sécurité du site.' },
      ] },
      { title: 'Prestataires et transferts', blocks: [{ type: 'text', text: 'Le site s’appuie sur des prestataires techniques pouvant traiter certaines données pour son compte : Vercel pour l’hébergement et le déploiement, Neon/PostgreSQL pour la persistance, Resend pour les emails, Google (Gemini) et Groq pour le traitement des messages par l’assistant IA et le calcul de devis, Cloudinary pour certains médias, ainsi que Vercel Analytics pour la mesure d’audience.' }, { type: 'text', text: 'Ces prestataires peuvent être établis en dehors de la Côte d’Ivoire. AKATech Studio sélectionne les services nécessaires au fonctionnement du site et leur transmet uniquement les données utiles à leur mission.' }] },
      { title: 'Cadre légal applicable', blocks: [{ type: 'text', text: 'Ce traitement de données personnelles est encadré par la loi n° 2013-450 du 19 juin 2013 relative à la protection des données à caractère personnel en Côte d’Ivoire, dont le respect est contrôlé par l’ARTCI.' }] },
      { title: 'Cookies et conservation', blocks: [{ type: 'text', text: 'Une bannière vous permet de choisir : les cookies essentiels au fonctionnement du site et à une mesure d’audience anonyme restent actifs dans tous les cas, tandis que les cookies analytiques ne sont activés qu’avec votre accord. Votre choix est mémorisé sur votre appareil et vous pouvez le modifier à tout moment.' }, { type: 'text', text: 'Les données sont conservées pendant une durée proportionnée à la finalité : le temps du traitement de la demande, du suivi commercial ou des obligations applicables.' }] },
      { title: 'Vos droits', blocks: [{ type: 'text', text: 'Vous pouvez demander l’accès, la rectification, la suppression, la limitation ou l’opposition au traitement de vos données, lorsque ces droits sont applicables. Vous pouvez également retirer un consentement donné.' }, { type: 'text', text: 'Pour exercer un droit, écrivez à wthomasss06@gmail.com en précisant votre demande. Une vérification raisonnable de votre identité peut être demandée.' }, { type: 'text', text: 'Vous disposez également du droit d’introduire une réclamation auprès de l’ARTCI.' }] },
    ] },
    en: { eyebrow: 'AKATech Studio · Personal data', title: 'Privacy policy', intro: 'AKATech Studio explains what data is used, why it is used and how you can exercise your rights.', sections: [
      { title: 'Controller and contact', blocks: [{ type: 'text', text: 'The controller is AKATech Studio, based in Abidjan, Côte d’Ivoire. For any request about your data: wthomasss06@gmail.com.' }] },
      { title: 'Data collected', blocks: [{ type: 'text', text: 'Depending on the journey you use, the website may process information you voluntarily provide: your name or company name, email address, phone number, project type, budget, timeline, messages and quote-questionnaire answers.' }, { type: 'text', text: 'The website may also receive technical data needed to operate it: IP address or limited technical fingerprint, browser, device, pages viewed, referral source and session identifiers.' }, { type: 'text', text: 'Do not send sensitive data or confidential documents in chat or forms unless they are necessary for your request.' }] },
      { title: 'Purposes and legal bases', blocks: [{ type: 'list', items: ['Answer requests sent through the contact form or AI assistant.', 'Qualify a need and generate an estimated quote from the information provided.', 'Keep the history needed for sales follow-up and service security.', 'Measure traffic and improve reliability where consent or another applicable legal basis allows it.'] }, { type: 'text', text: 'Data is used only for the requested service, prospect relationship management, and website operation and security.' }] },
      { title: 'Providers and transfers', blocks: [{ type: 'text', text: 'Technical providers may process data on our behalf: Vercel for hosting, Neon/PostgreSQL for persistence, Resend for email, Google (Gemini) and Groq for AI-assistant messages and quote calculations, Cloudinary for some media, and Vercel Analytics for audience measurement.' }, { type: 'text', text: 'These providers may be located outside Côte d’Ivoire. AKATech Studio shares only the information needed for their mission.' }] },
      { title: 'Applicable legal framework', blocks: [{ type: 'text', text: 'This processing is governed by Côte d’Ivoire Law no. 2013-450 of 19 June 2013 on the protection of personal data, overseen by ARTCI.' }] },
      { title: 'Cookies and retention', blocks: [{ type: 'text', text: 'A banner lets you choose: essential cookies and anonymous audience measurement remain active, while analytics cookies are enabled only with your consent. Your choice is stored on your device and can be changed at any time.' }, { type: 'text', text: 'Data is kept for a period proportionate to the purpose: while the request is handled, for sales follow-up or for applicable legal obligations.' }] },
      { title: 'Your rights', blocks: [{ type: 'text', text: 'Where applicable, you may request access, correction, deletion, restriction or objection to processing, and you may withdraw consent.' }, { type: 'text', text: 'To exercise a right, email wthomasss06@gmail.com and describe your request. A reasonable identity check may be required.' }, { type: 'text', text: 'You may also lodge a complaint with ARTCI.' }] },
    ] },
    es: { eyebrow: 'AKATech Studio · Datos personales', title: 'Política de privacidad', intro: 'AKATech Studio explica qué datos utiliza, por qué los utiliza y cómo ejercer tus derechos.', sections: [
      { title: 'Responsable y contacto', blocks: [{ type: 'text', text: 'El responsable es AKATech Studio, con sede en Abiyán, Costa de Marfil. Para cualquier solicitud sobre tus datos: wthomasss06@gmail.com.' }] },
      { title: 'Datos recopilados', blocks: [{ type: 'text', text: 'Según el recorrido utilizado, el sitio puede tratar los datos que proporcionas voluntariamente: nombre o empresa, correo electrónico, teléfono, tipo de proyecto, presupuesto, plazo, mensajes y respuestas al cuestionario.' }, { type: 'text', text: 'También puede recibir datos técnicos necesarios para funcionar: dirección IP o huella técnica limitada, navegador, dispositivo, páginas visitadas, origen de la visita e identificadores de sesión.' }, { type: 'text', text: 'No envíes datos sensibles ni documentos confidenciales en el chat o los formularios si no son necesarios.' }] },
      { title: 'Finalidades y bases', blocks: [{ type: 'list', items: ['Responder a las solicitudes del formulario de contacto o del asistente de IA.', 'Calificar una necesidad y generar un presupuesto estimado con la información recibida.', 'Conservar el historial necesario para el seguimiento comercial y la seguridad.', 'Medir la audiencia y mejorar la fiabilidad cuando el consentimiento o la base legal lo permitan.'] }, { type: 'text', text: 'Los datos solo se utilizan para el servicio solicitado, la relación con el prospecto y el funcionamiento y seguridad del sitio.' }] },
      { title: 'Proveedores y transferencias', blocks: [{ type: 'text', text: 'Algunos proveedores técnicos pueden tratar datos por nuestra cuenta: Vercel, Neon/PostgreSQL, Resend, Google (Gemini), Groq, Cloudinary y Vercel Analytics.' }, { type: 'text', text: 'Pueden estar fuera de Costa de Marfil. AKATech Studio comparte únicamente la información necesaria para su misión.' }] },
      { title: 'Marco legal aplicable', blocks: [{ type: 'text', text: 'Este tratamiento se rige por la Ley marfileña n.º 2013-450 de 19 de junio de 2013 sobre protección de datos personales, supervisada por la ARTCI.' }] },
      { title: 'Cookies y conservación', blocks: [{ type: 'text', text: 'Un banner permite elegir: las cookies esenciales y la medición anónima permanecen activas, mientras que las cookies analíticas solo se activan con tu consentimiento. Puedes cambiar tu elección en cualquier momento.' }, { type: 'text', text: 'Los datos se conservan durante un periodo proporcional a su finalidad: gestión de la solicitud, seguimiento comercial u obligaciones legales.' }] },
      { title: 'Tus derechos', blocks: [{ type: 'text', text: 'Cuando corresponda, puedes solicitar acceso, rectificación, eliminación, limitación u oposición al tratamiento y retirar tu consentimiento.' }, { type: 'text', text: 'Para ejercer un derecho, escribe a wthomasss06@gmail.com describiendo tu solicitud. Puede pedirse una verificación razonable de identidad.' }, { type: 'text', text: 'También puedes presentar una reclamación ante la ARTCI.' }] },
    ] },
  },
  terms: {
    fr: { eyebrow: 'AKATech Studio · Règles du site', title: 'Conditions d’utilisation', intro: 'Ces conditions expliquent le cadre d’utilisation du site, de l’assistant IA et du parcours de devis AKATech.', sections: [
      { title: 'Objet', blocks: [{ type: 'text', text: 'Les présentes conditions définissent les règles d’accès et d’utilisation du site AKATech Studio. En naviguant sur le site, vous acceptez ces conditions dans leur version applicable au moment de votre visite.' }, { type: 'text', text: 'Les prestations de développement, de maintenance ou d’accompagnement font l’objet de conditions commerciales ou contractuelles distinctes lorsqu’un projet est engagé.' }] },
      { title: 'Accès au site', blocks: [{ type: 'text', text: 'Le site est accessible gratuitement, hors coût de connexion et d’équipement. AKATech Studio peut suspendre temporairement une partie du service pour maintenance, sécurité, mise à jour ou raison indépendante de sa volonté.' }, { type: 'text', text: 'L’utilisateur s’engage à ne pas perturber le fonctionnement du site, contourner ses mesures de sécurité, envoyer des contenus illicites ou utiliser l’assistant pour une finalité frauduleuse.' }] },
      { title: 'Assistant IA et parcours de devis', blocks: [{ type: 'text', text: 'L’assistant IA fournit une aide d’orientation et de qualification. Ses réponses ne constituent pas un conseil juridique, financier ou professionnel et ne remplacent pas l’échange avec AKATech Studio.' }, { type: 'text', text: 'Le questionnaire peut produire une estimation à partir des informations saisies et de la grille tarifaire disponible. Cette estimation n’est pas un engagement contractuel tant qu’un devis ou une proposition commerciale n’a pas été explicitement validé par AKATech Studio.' }, { type: 'text', text: 'L’utilisateur est responsable de l’exactitude, de la licéité et de la confidentialité des informations transmises dans le chat et les formulaires.' }] },
      { title: 'Propriété intellectuelle', blocks: [{ type: 'text', text: 'Les contenus, interfaces, textes, visuels, logiciels et éléments de marque du site sont protégés. Aucun droit de reproduction, de modification, de revente ou d’exploitation n’est accordé en dehors de l’usage normal du site.' }] },
      { title: 'Liens et services tiers', blocks: [{ type: 'text', text: 'Le site peut contenir des liens vers des services ou sites tiers. AKATech Studio ne contrôle pas leurs contenus, leurs disponibilités ni leurs politiques de confidentialité et ne peut être responsable de leur fonctionnement.' }] },
      { title: 'Responsabilité', blocks: [{ type: 'text', text: 'AKATech Studio met en œuvre des moyens raisonnables pour maintenir des informations accessibles et un service fiable. Aucune garantie de disponibilité permanente, d’absence d’erreur ou de résultat commercial n’est donnée pour le site, l’assistant ou une estimation automatique.' }, { type: 'text', text: 'Les présentes conditions n’excluent pas les responsabilités qui ne peuvent pas l’être en vertu des règles applicables.' }] },
      { title: 'Droit applicable et contact', blocks: [{ type: 'text', text: 'Les présentes conditions sont soumises aux règles applicables en Côte d’Ivoire, sous réserve des dispositions impératives qui pourraient s’appliquer à l’utilisateur.' }, { type: 'text', text: 'Toute question concernant ces conditions peut être envoyée à wthomasss06@gmail.com.' }] },
    ] },
    en: { eyebrow: 'AKATech Studio · Website rules', title: 'Terms of use', intro: 'These terms explain the framework for using the AKATech website, AI assistant and quote journey.', sections: [
      { title: 'Purpose', blocks: [{ type: 'text', text: 'These terms define access to and use of the AKATech Studio website. By browsing it, you accept the version applicable at the time of your visit.' }, { type: 'text', text: 'Development, maintenance and consulting services are governed by separate commercial or contractual terms when a project begins.' }] },
      { title: 'Access', blocks: [{ type: 'text', text: 'The website is free to access, excluding connection and equipment costs. AKATech Studio may temporarily suspend a service for maintenance, security, updates or circumstances beyond its control.' }, { type: 'text', text: 'Users must not disrupt the website, bypass security measures, submit unlawful content or use the assistant for fraudulent purposes.' }] },
      { title: 'AI assistant and quote journey', blocks: [{ type: 'text', text: 'The AI assistant provides guidance and qualification help. Its answers are not legal, financial or professional advice and do not replace a discussion with AKATech Studio.' }, { type: 'text', text: 'The questionnaire may produce an estimate from the information entered and the available price grid. It is not a contractual commitment until AKATech Studio expressly approves a quote or commercial proposal.' }, { type: 'text', text: 'Users are responsible for the accuracy, lawfulness and confidentiality of information submitted in chat and forms.' }] },
      { title: 'Intellectual property', blocks: [{ type: 'text', text: 'Website content, interfaces, copy, visuals, software and brand elements are protected. No right to reproduce, modify, resell or exploit them is granted beyond normal website use.' }] },
      { title: 'Links and third-party services', blocks: [{ type: 'text', text: 'The website may link to third-party services or websites. AKATech Studio does not control their content, availability or privacy policies and is not responsible for their operation.' }] },
      { title: 'Liability', blocks: [{ type: 'text', text: 'AKATech Studio takes reasonable steps to keep information accessible and the service reliable. No guarantee of continuous availability, error-free operation or commercial results is given for the website, assistant or automated estimate.' }, { type: 'text', text: 'These terms do not exclude liabilities that cannot be excluded under applicable rules.' }] },
      { title: 'Applicable law and contact', blocks: [{ type: 'text', text: 'These terms are governed by applicable Côte d’Ivoire rules, subject to mandatory provisions that may apply to the user.' }, { type: 'text', text: 'Questions about these terms can be sent to wthomasss06@gmail.com.' }] },
    ] },
    es: { eyebrow: 'AKATech Studio · Reglas del sitio', title: 'Condiciones de uso', intro: 'Estas condiciones explican el marco de uso del sitio, del asistente de IA y del proceso de presupuesto de AKATech.', sections: [
      { title: 'Objeto', blocks: [{ type: 'text', text: 'Estas condiciones definen el acceso y uso del sitio de AKATech Studio. Al navegar, aceptas la versión vigente durante tu visita.' }, { type: 'text', text: 'Los servicios de desarrollo, mantenimiento o asesoría se rigen por condiciones comerciales o contractuales distintas cuando comienza un proyecto.' }] },
      { title: 'Acceso al sitio', blocks: [{ type: 'text', text: 'El acceso es gratuito, salvo los costes de conexión y equipo. AKATech Studio puede suspender temporalmente el servicio por mantenimiento, seguridad, actualizaciones o causas ajenas a su voluntad.' }, { type: 'text', text: 'El usuario no debe perturbar el funcionamiento, eludir las medidas de seguridad, enviar contenido ilícito ni utilizar el asistente con fines fraudulentos.' }] },
      { title: 'Asistente de IA y presupuesto', blocks: [{ type: 'text', text: 'El asistente de IA ofrece orientación y ayuda para calificar necesidades. Sus respuestas no son asesoramiento jurídico, financiero o profesional y no sustituyen una conversación con AKATech Studio.' }, { type: 'text', text: 'El cuestionario puede generar una estimación a partir de los datos introducidos y de la tarifa disponible. No es un compromiso contractual hasta que AKATech Studio apruebe expresamente un presupuesto o propuesta.' }, { type: 'text', text: 'El usuario es responsable de la exactitud, legalidad y confidencialidad de la información enviada en el chat y los formularios.' }] },
      { title: 'Propiedad intelectual', blocks: [{ type: 'text', text: 'Los contenidos, interfaces, textos, elementos visuales, software y marca del sitio están protegidos. No se concede ningún derecho de reproducción, modificación, reventa o explotación fuera del uso normal del sitio.' }] },
      { title: 'Enlaces y servicios de terceros', blocks: [{ type: 'text', text: 'El sitio puede enlazar con servicios o sitios de terceros. AKATech Studio no controla su contenido, disponibilidad ni políticas de privacidad y no responde por su funcionamiento.' }] },
      { title: 'Responsabilidad', blocks: [{ type: 'text', text: 'AKATech Studio aplica medios razonables para mantener la información accesible y el servicio fiable. No garantiza disponibilidad permanente, ausencia de errores ni resultados comerciales.' }, { type: 'text', text: 'Estas condiciones no excluyen las responsabilidades que no puedan excluirse según las normas aplicables.' }] },
      { title: 'Ley aplicable y contacto', blocks: [{ type: 'text', text: 'Estas condiciones se someten a las normas aplicables en Costa de Marfil, sin perjuicio de las disposiciones imperativas que puedan aplicarse al usuario.' }, { type: 'text', text: 'Las preguntas sobre estas condiciones pueden enviarse a wthomasss06@gmail.com.' }] },
    ] },
  },
}
