from pathlib import Path
p=Path('/home/ubuntu/akatech-work/lib/language.js')
s=p.read_text()
repls={
"project_type: 'Type', project_market: 'Marché', project_role: 'Mon rôle', project_year: 'Année', project_view: 'Voir le projet', project_demo: 'Démo locale', project_progress: 'En cours',": "project_type: 'Type', project_market: 'Marché', project_role: 'Mon rôle', project_year: 'Année', project_view: 'Voir le projet', project_demo: 'Démo locale', project_progress: 'En cours', project_country: \"Côte d'Ivoire\", project_design: 'Conception & Développement', projectsTitleUpper: 'RÉALISATIONS', projectsScrollHint: 'Défilez pour parcourir', projectsCountHeading: '{count} réalisations, une par une.', projectsCtaTitle: 'VOTRE PROJET, NOTRE PROCHAIN SUCCÈS ?', projectsCtaLead: 'Votre projet,', projectsCtaHighlight: 'notre prochain succès ?', projectsIntro: 'Ci-dessous : des projets réalisés pour des PME, startups et créateurs. Découvrez les objectifs, technologies et résultats de chaque réalisation sur mesure.', caseProblem: 'Problème', caseSolution: 'Solution', caseResult: 'Résultat', status: 'Statut',",
"project_type: 'Type', project_market: 'Market', project_role: 'My role', project_year: 'Year', project_view: 'View project', project_demo: 'Local demo', project_progress: 'In progress',": "project_type: 'Type', project_market: 'Market', project_role: 'My role', project_year: 'Year', project_view: 'View project', project_demo: 'Local demo', project_progress: 'In progress', project_country: \"Côte d’Ivoire\", project_design: 'Design & Development', projectsTitleUpper: 'PROJECTS', projectsScrollHint: 'Scroll to browse', projectsCountHeading: '{count} projects, one by one.', projectsCtaTitle: 'YOUR PROJECT, OUR NEXT SUCCESS?', projectsCtaLead: 'Your project,', projectsCtaHighlight: 'our next success?', projectsIntro: 'Below: projects built for SMEs, startups and creators. Explore the goals, technologies and results behind each tailor-made project.', caseProblem: 'Challenge', caseSolution: 'Solution', caseResult: 'Result', status: 'Status',",
"project_type: 'Tipo', project_market: 'Mercado', project_role: 'Mi rol', project_year: 'Año', project_view: 'Ver proyecto', project_demo: 'Demo local', project_progress: 'En curso',": "project_type: 'Tipo', project_market: 'Mercado', project_role: 'Mi rol', project_year: 'Año', project_view: 'Ver proyecto', project_demo: 'Demo local', project_progress: 'En curso', project_country: 'Costa de Marfil', project_design: 'Diseño y desarrollo', projectsTitleUpper: 'PROYECTOS', projectsScrollHint: 'Desplázate para navegar', projectsCountHeading: '{count} proyectos, uno por uno.', projectsCtaTitle: '¿TU PROYECTO, NUESTRO PRÓXIMO ÉXITO?', projectsCtaLead: 'Tu proyecto,', projectsCtaHighlight: '¿nuestro próximo éxito?', projectsIntro: 'A continuación: proyectos realizados para pymes, startups y creadores. Descubre los objetivos, tecnologías y resultados de cada proyecto a medida.', caseProblem: 'Problema', caseSolution: 'Solución', caseResult: 'Resultado', status: 'Estado',"
}
for a,b in repls.items():
    if a not in s: print('missing',a[:30])
    s=s.replace(a,b)
p.write_text(s)
