from pathlib import Path
p=Path('/home/ubuntu/akatech-work/lib/language.js')
s=p.read_text()
fr="homeHeroText: 'Lancez un site professionnel qui inspire confiance et déclenche des demandes.',"
en="homeHeroText: 'Launch a professional website that builds trust and generates enquiries.',"
es="homeHeroText: 'Lanza un sitio profesional que inspire confianza y genere solicitudes.',"
vals={fr:"homeHeroText: 'Lancez un site professionnel qui inspire confiance et déclenche des demandes.', viewService: 'Voir le service', viewAllProjects: 'Voir tous les projets', homeProjectsUpper: 'NOS DERNIÈRES RÉALISATIONS', homeTestimonialsUpper: 'CE QUE DISENT NOS CLIENTS', faqUpper: 'QUESTIONS FRÉQUENTES', geoUpper: 'OÙ INTERVENONS-NOUS ?', formUpper: 'DÉCRIVEZ VOTRE PROJET', receiveQuote: 'Recevoir mon devis en 24h', sendAnother: 'Envoyer un autre message', writeUs: 'Nous écrire', formSuccess: 'Votre demande a bien été reçue. On répond en moins de 24h directement par email — à très vite !', yourName: 'Votre nom', yourNeed: 'Votre besoin en une phrase', projectTypeLabel: 'Type de projet', chooseLabel: 'Choisir...', privacyNote: 'Vos données restent confidentielles. Aucun spam.', messageSent: 'Message envoyé !',", en:"homeHeroText: 'Launch a professional website that builds trust and generates enquiries.', viewService: 'View service', viewAllProjects: 'View all projects', homeProjectsUpper: 'OUR LATEST WORK', homeTestimonialsUpper: 'WHAT OUR CLIENTS SAY', faqUpper: 'FREQUENTLY ASKED QUESTIONS', geoUpper: 'WHERE WE WORK', formUpper: 'DESCRIBE YOUR PROJECT', receiveQuote: 'Get my quote within 24h', sendAnother: 'Send another message', writeUs: 'Write to us', formSuccess: 'Your request was received. We reply by email within 24 hours — talk soon!', yourName: 'Your name', yourNeed: 'Your need in one sentence', projectTypeLabel: 'Project type', chooseLabel: 'Choose...', privacyNote: 'Your data stays confidential. No spam.', messageSent: 'Message sent!',", es:"homeHeroText: 'Lanza un sitio profesional que inspire confianza y genere solicitudes.', viewService: 'Ver el servicio', viewAllProjects: 'Ver todos los proyectos', homeProjectsUpper: 'NUESTROS ÚLTIMOS PROYECTOS', homeTestimonialsUpper: 'LO QUE DICEN NUESTROS CLIENTES', faqUpper: 'PREGUNTAS FRECUENTES', geoUpper: 'DÓNDE TRABAJAMOS', formUpper: 'DESCRIBE TU PROYECTO', receiveQuote: 'Recibir mi presupuesto en 24h', sendAnother: 'Enviar otro mensaje', writeUs: 'Escríbenos', formSuccess: 'Recibimos tu solicitud. Respondemos por email en menos de 24 horas — ¡hasta pronto!', yourName: 'Tu nombre', yourNeed: 'Tu necesidad en una frase', projectTypeLabel: 'Tipo de proyecto', chooseLabel: 'Elegir...', privacyNote: 'Tus datos son confidenciales. Sin spam.', messageSent: '¡Mensaje enviado!',"}
for a,b in vals.items():
 if a not in s: print('missing',a)
 s=s.replace(a,b)
p.write_text(s)
